comment:
  layout: 'reach,diff,flags,footer'
  behavior: default
  require_changes: true

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 0%

flags:
  node:
    paths:
      - coverage/lcov.info
